version: '2'
services:
    ugd-app:
        image: ugd
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ugd-postgresql:5432/UGD
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ugd-postgresql:
        extends:
            file: postgresql.yml
            service: ugd-postgresql
